### ISSUE TITLE
Jekyll Sitemap broken with HEAD

### ISSUE THREAD

**Issue by envygeeks** [jekyll/jekyll-sitemap#123]
```
jordon@tardis ~/development/jekyll/jekyll/site (master u=) → rm -rf _site; time bundle exec jekyll b --trace
Configuration file: /home/jordon/development/jekyll/jekyll/site/_config.yml
            Source: /home/jordon/development/jekyll/jekyll/site
       Destination: /home/jordon/development/jekyll/jekyll/site/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
/home/jordon/development/jekyll/jekyll/vendor/bundle/ruby/2.3.0/gems/jekyll-sitemap-0.11.0/lib/jekyll/jekyll-sitemap.rb:57:in `sitemap_content': undefined method `gsub' for nil:NilClass (NoMethodError)
	from /home/jordon/development/jekyll/jekyll/vendor/bundle/ruby/2.3.0/gems/jekyll-sitemap-0.11.0/lib/jekyll/jekyll-sitemap.rb:48:in `block in write'
	from /home/jordon/development/jekyll/jekyll/vendor/bundle/ruby/2.3.0/gems/jekyll-sitemap-0.11.0/lib/jekyll/jekyll-sitemap.rb:48:in `open'
	from /home/jordon/development/jekyll/jekyll/vendor/bundle/ruby/2.3.0/gems/jekyll-sitemap-0.11.0/lib/jekyll/jekyll-sitemap.rb:48:in `write'
	from /home/jordon/development/jekyll/jekyll/vendor/bundle/ruby/2.3.0/gems/jekyll-sitemap-0.11.0/lib/jekyll/jekyll-sitemap.rb:13:in `generate'
	from /home/jordon/development/jekyll/jekyll/lib/jekyll/site.rb:174:in `block in generate'
	from /home/jordon/development/jekyll/jekyll/lib/jekyll/site.rb:172:in `each'
	from /home/jordon/development/jekyll/jekyll/lib/jekyll/site.rb:172:in `generate'
	from /home/jordon/development/jekyll/jekyll/lib/jekyll/site.rb:68:in `process'
	from /home/jordon/development/jekyll/jekyll/lib/jekyll/command.rb:26:in `process_site'
	from /home/jordon/development/jekyll/jekyll/lib/jekyll/commands/build.rb:63:in `build'
	from /home/jordon/development/jekyll/jekyll/lib/jekyll/commands/build.rb:34:in `process'
	from /home/jordon/development/jekyll/jekyll/lib/jekyll/commands/build.rb:16:in `block (2 levels) in init_with_program'
	from /home/jordon/development/jekyll/jekyll/vendor/bundle/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /home/jordon/development/jekyll/jekyll/vendor/bundle/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /home/jordon/development/jekyll/jekyll/vendor/bundle/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /home/jordon/development/jekyll/jekyll/vendor/bundle/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /home/jordon/development/jekyll/jekyll/vendor/bundle/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /home/jordon/development/jekyll/jekyll/exe/jekyll:13:in `<top (required)>'
	from /home/jordon/development/jekyll/jekyll/vendor/bundle/ruby/2.3.0/bin/jekyll:23:in `load'
	from /home/jordon/development/jekyll/jekyll/vendor/bundle/ruby/2.3.0/bin/jekyll:23:in `<main>'

real	0m1.022s
user	0m0.944s
sys	0m0.072s
```

**Comment by envygeeks** [comment]
Jekyll bug, closing in favor of that ticket.
