### ISSUE TITLE
`jekyll-sitemap.rb` error in `bundle exec rake site:preview` command

### ISSUE THREAD

**Issue by SuriyaaKudoIsc** [jekyll/jekyll-sitemap#124]
**I got issues from jekyll-sitemap in `bundle exec rake site:preview`.** It doesn't worked on *Windows 10 [build 14393]*:

```
...
C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-sitemap-0.11.0/lib/jekyll/jekyll-sitemap.rb:57:in `sitemap_content'
C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-sitemap-0.11.0/lib/jekyll/jekyll-sitemap.rb:48:in `block in write'
C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-sitemap-0.11.0/lib/jekyll/jekyll-sitemap.rb:48:in `open'
C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-sitemap-0.11.0/lib/jekyll/jekyll-sitemap.rb:48:in `write'
C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-sitemap-0.11.0/lib/jekyll/jekyll-sitemap.rb:13:in `generate'
...
```

> See issue https://github.com/jekyll/jekyll/issues/4928#issuecomment-244914353!

**Comment by benbalter** [comment]
> NoMethodError: undefined method `gsub' for nil:NilClass

I suspect it may not be properly building the path to the internal template.

**Comment by benbalter** [comment]
Also possibly related to https://github.com/jekyll/jekyll-sitemap/issues/123.
